#!/usr/bin/env python3
import sys
import os

AEGIS_ROOT = "/home/gaurav/Projects/Aegis"
if AEGIS_ROOT not in sys.path:
    sys.path.insert(0, AEGIS_ROOT)

from aegis.main import main

if __name__ == "__main__":
    main()
